### ISSUE TITLE
White Paper: Google Docs links

### ISSUE THREAD

**Issue by IvanRF** [GoodDollar/GoodBootstrap#23]
[Monetary Tools and Controls](https://whitepaper.gooddollar.org/monetary-tools-and-controls) has 3 links to Google Docs:
https://docs.google.com/document/d/1n-1oH89oYILDCTX4RgQZbDYSOqIYuGOfzkGAejThEuY/edit

I think those links are wrong.

Governance = https://whitepaper.gooddollar.org/governance
Equation 3 = https://whitepaper.gooddollar.org/appendix#equation-3-expansion-rate-formula
Reserve Ratio = https://whitepaper.gooddollar.org/appendix#equation-1-reserve-ratio-equation

**Comment by sirpy** [comment]
Thanks!! 
I have fixed the links 

Good looking out Ivan! 

Cheers, Amit. 

Creative Lead
